adding db
Sanyyouisf/Mushroom-Mania pull request #2
Opened 2017-05-13 18:46 UTC by Sanyyouisf

2017-05-14 03:03 UTC, Sanyyouisf commented
@drdreed
finish

2017-05-20 18:39 UTC, drdreed commented on index.html
> +		        		<button class="btn btn-default" type="button" ng-click="showSearch()">Go!</button>
Code needs formatted.

2017-05-20 18:40 UTC, drdreed commented on javascripts/main.js
> +        console.log(" you click showSearch");
Remove console logs.

2017-05-20 18:41 UTC, DevDreed requested changes
Just a couple minor details.

2017-07-10 22:58 UTC, merged